import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Silvija',
      email: 'admin@duokduonos.lt',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Kazkas',
      email: 'admin@duokduonos.lt',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],


    products: [
      {
        _id: '1',
        name: 'Duona iš raugo - Sourdough',
        category: 'bread',
        image: '/images/p1.jpg',
        price: 3.5,
        countInStock: 20,
        brand: 'Silvija',
        rating: 4.5,
        numReviews: 10,
        description: 'ekoligiškų miltų raugo duona',
      },
      {
        _id: '2',
        name: 'Cinamoninės bandelės',
        category: 'buns',
        image: '/images/p2.jpg',
        price: 2,
        countInStock: 0,
        brand: 'Silvija',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Itališka duona - Focaccia',
        category: 'bread',
        image: '/images/p3.jpg',
        price: 3.5,
        countInStock: 10,
        brand: 'Silvija',
        rating: 1,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Prancūziška duona - Brioche',
        category: 'bread',
        image: '/images/p4.jpg',
        price: 5,
        countInStock: 30,
        brand: 'Silvija',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Prancūziška duona - Bagetė',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 2,
        countInStock: 3,
        brand: 'kazkas',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Sausainiai su šokolado gabaliukais',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 1,
        brand: 'kazkas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Naminė juoda duona',
        category: 'Pants',
        image: '/images/p7.jpg',
        price: 2.5,
        brand: 'kazkas',
        rating: 2,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Kalėdiniai meduoliai',
        category: 'Pants',
        image: '/images/p8.jpg',
        price: 1,
        brand: 'kazkas',
        rating: 3,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;