const data = {
    products: [
      {
        _id: '1',
        name: 'Duona iš raugo - Sourdough',
        category: 'bread',
        image: '/images/p1.jpg',
        price: 3.5,
        brand: 'Silvija',
        rating: 4.5,
        numReviews: 10,
        description: 'ekoligiškų miltų raugo duona',
      },
      {
        _id: '2',
        name: 'Cinamoninės bandelės',
        category: 'buns',
        image: '/images/p2.jpg',
        price: 2,
        brand: 'Silvija',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Itališka duona - Focaccia',
        category: 'bread',
        image: '/images/p3.jpg',
        price: 3.5,
        brand: 'Silvija',
        rating: 1,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Prancūziška duona - Brioche',
        category: 'bread',
        image: '/images/p4.jpg',
        price: 5,
        brand: 'Silvija',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Prancūziška duona - Bagetė',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 2,
        brand: 'kazkas',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Sausainiai su šokolado gabaliukais',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 1,
        brand: 'kazkas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;